# Generated by Django 4.2.10 on 2025-03-25 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods_receipt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="legal name"
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Manufacturer"),
                            ("distributor", "Distributor"),
                            ("wholesaler", "Wholesaler"),
                            ("retailer", "Retailer"),
                            ("other", "Other"),
                        ],
                        default="distributor",
                        max_length=20,
                        verbose_name="supplier type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="tax ID"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="registration number"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="state"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="credit limit",
                    ),
                ),
                (
                    "credit_period",
                    models.PositiveIntegerField(
                        default=0, verbose_name="credit period (days)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_by", models.UUIDField(verbose_name="created by")),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name="invoice number"),
                ),
                ("invoice_date", models.DateField(verbose_name="invoice date")),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="subtotal"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="shipping amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total amount"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="balance due"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "invoice_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="supplier_invoices/",
                        verbose_name="invoice image",
                    ),
                ),
                ("created_by", models.UUIDField(verbose_name="created by")),
                (
                    "verified_by",
                    models.UUIDField(blank=True, null=True, verbose_name="verified by"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verified at"
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="goods_receipt.goodsreceipt",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier invoice",
                "verbose_name_plural": "supplier invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                ("product_id", models.UUIDField(verbose_name="product ID")),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="product name"),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="product code"),
                ),
                (
                    "supplier_product_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="supplier product code"
                    ),
                ),
                (
                    "supplier_product_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="supplier product name"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="unit price"
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        verbose_name="minimum order quantity",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="lead time (days)"
                    ),
                ),
                (
                    "is_preferred_supplier",
                    models.BooleanField(
                        default=False, verbose_name="is preferred supplier"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_by", models.UUIDField(verbose_name="created by")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier product",
                "verbose_name_plural": "supplier products",
                "ordering": ["product_name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                (
                    "payment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="payment number"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="payment date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("upi", "UPI"),
                            ("credit", "Credit"),
                        ],
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="reference number"
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="cheque number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_by", models.UUIDField(verbose_name="created by")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier payment",
                "verbose_name_plural": "supplier payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoicePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="suppliers.supplierinvoice",
                    ),
                ),
                (
                    "supplier_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_payments",
                        to="suppliers.supplierpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier invoice payment",
                "verbose_name_plural": "supplier invoice payments",
            },
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="designation"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="department"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=20, verbose_name="mobile"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="is primary"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier contact",
                "verbose_name_plural": "supplier contacts",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["tenant_id", "name"], name="suppliers_s_tenant__566edc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["tenant_id", "status"], name="suppliers_s_tenant__bd9ec7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["code"], name="suppliers_s_code_d1984e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="supplierproduct",
            unique_together={("supplier", "product_id", "shop_id")},
        ),
        migrations.AlterUniqueTogether(
            name="supplierinvoicepayment",
            unique_together={("supplier_payment", "supplier_invoice")},
        ),
        migrations.AlterUniqueTogether(
            name="supplierinvoice",
            unique_together={("supplier", "invoice_number")},
        ),
    ]
