apiVersion: v1
kind: Secret
metadata:
  name: liquor-secrets
  namespace: liquor-system
type: Opaque
data:
  # These are base64 encoded values
  # echo -n "django-insecure-key-for-dev-only" | base64
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWtleS1mb3ItZGV2LW9ubHk=
  # echo -n "liquor_user" | base64
  DB_USER: bGlxdW9yX3VzZXI=
  # echo -n "liquor_password" | base64
  DB_PASSWORD: bGlxdW9yX3Bhc3N3b3Jk
