apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: liquor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ${DOCKER_REGISTRY}/liquor-backend/auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: liquor-config
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: liquor-secrets
              key: SECRET_KEY
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: liquor-config
              key: ALLOWED_HOSTS
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: liquor-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: liquor-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: liquor-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: liquor-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: liquor-config
              key: DB_PORT
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: liquor-config
              key: REDIS_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: liquor-config
              key: KAFKA_BOOTSTRAP_SERVERS
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        command:
        - sh
        - -c
        - |
          mkdir -p logs
          python manage.py migrate
          gunicorn auth_service.wsgi:application --bind 0.0.0.0:8000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: liquor-system
spec:
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
