# Generated by Django 4.2.10 on 2025-03-25 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                (
                    "approval_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="approval number"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="approval date"
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("stock_adjustment", "Stock Adjustment"),
                            ("deposit", "Deposit"),
                            ("expense", "Expense"),
                            ("discount", "Discount"),
                            ("batch_sale", "Batch Sale"),
                        ],
                        max_length=20,
                        verbose_name="approval type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                ("reference_id", models.UUIDField(verbose_name="reference ID")),
                (
                    "reference_number",
                    models.CharField(max_length=50, verbose_name="reference number"),
                ),
                (
                    "reference_data",
                    models.JSONField(default=dict, verbose_name="reference data"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("requested_by", models.UUIDField(verbose_name="requested by")),
                (
                    "requested_by_name",
                    models.CharField(max_length=100, verbose_name="requested by name"),
                ),
                (
                    "approved_by",
                    models.UUIDField(blank=True, null=True, verbose_name="approved by"),
                ),
                (
                    "approved_by_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="approved by name"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
            ],
            options={
                "verbose_name": "approval",
                "verbose_name_plural": "approvals",
                "ordering": ["-approval_date"],
            },
        ),
        migrations.CreateModel(
            name="BatchApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="batch number"
                    ),
                ),
                (
                    "batch_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="batch date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "total_approvals",
                    models.IntegerField(default=0, verbose_name="total approvals"),
                ),
                (
                    "approved_count",
                    models.IntegerField(default=0, verbose_name="approved count"),
                ),
                (
                    "rejected_count",
                    models.IntegerField(default=0, verbose_name="rejected count"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("processed_by", models.UUIDField(verbose_name="processed by")),
                (
                    "processed_by_name",
                    models.CharField(max_length=100, verbose_name="processed by name"),
                ),
            ],
            options={
                "verbose_name": "batch approval",
                "verbose_name_plural": "batch approvals",
                "ordering": ["-batch_date"],
            },
        ),
        migrations.CreateModel(
            name="BatchApprovalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("approve", "Approve"), ("reject", "Reject")],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_items",
                        to="approvals.approval",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="approvals.batchapproval",
                    ),
                ),
            ],
            options={
                "verbose_name": "batch approval item",
                "verbose_name_plural": "batch approval items",
            },
        ),
        migrations.CreateModel(
            name="ApprovalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("tenant_id", models.UUIDField(verbose_name="tenant ID")),
                ("shop_id", models.UUIDField(verbose_name="shop ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("resubmitted", "Resubmitted"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "action_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="action date"),
                ),
                ("user_id", models.UUIDField(verbose_name="user ID")),
                (
                    "user_name",
                    models.CharField(max_length=100, verbose_name="user name"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="approvals.approval",
                    ),
                ),
            ],
            options={
                "verbose_name": "approval history",
                "verbose_name_plural": "approval history",
                "ordering": ["-action_date"],
            },
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["tenant_id", "shop_id", "approval_date"],
                name="approvals_a_tenant__4bdd16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["tenant_id", "shop_id", "status"],
                name="approvals_a_tenant__df0a4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["tenant_id", "shop_id", "approval_type"],
                name="approvals_a_tenant__9bbacb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["tenant_id", "shop_id", "requested_by"],
                name="approvals_a_tenant__8902d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["approval_number"], name="approvals_a_approva_33c08c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batchapprovalitem",
            unique_together={("batch", "approval")},
        ),
    ]
