version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: liquor_db
      POSTGRES_USER: liquor_user
      POSTGRES_PASSWORD: liquor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquor_user -d liquor_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: .
    environment:
      - SERVICE_NAME=auth
      - DATABASE_URL=postgres://liquor_user:liquor_password@postgres:5432/liquor_db
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
      - DJANGO_SETTINGS_MODULE=auth_service.settings
      - PYTHONPATH=/app:/app/src
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/auth_service/logs:/app/src/auth_service/logs

  core_service:
    build: .
    environment:
      - SERVICE_NAME=core
      - DATABASE_URL=postgres://liquor_user:liquor_password@postgres:5432/liquor_db
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
      - DJANGO_SETTINGS_MODULE=core_service.settings
      - PYTHONPATH=/app:/app/src
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/core_service/logs:/app/src/core_service/logs

  sales_service:
    build: .
    environment:
      - SERVICE_NAME=sales
      - DATABASE_URL=postgres://liquor_user:liquor_password@postgres:5432/liquor_db
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
      - DJANGO_SETTINGS_MODULE=sales_service.settings
      - PYTHONPATH=/app:/app/src
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/sales_service/logs:/app/src/sales_service/logs

  inventory_service:
    build: .
    environment:
      - SERVICE_NAME=inventory
      - DATABASE_URL=postgres://liquor_user:liquor_password@postgres:5432/liquor_db
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
      - DJANGO_SETTINGS_MODULE=inventory_service.settings
      - PYTHONPATH=/app:/app/src
    ports:
      - "8003:8003"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/inventory_service/logs:/app/src/inventory_service/logs

  purchase_service:
    build: .
    environment:
      - SERVICE_NAME=purchase
      - DATABASE_URL=postgres://liquor_user:liquor_password@postgres:5432/liquor_db
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
      - DJANGO_SETTINGS_MODULE=purchase_service.settings
      - PYTHONPATH=/app:/app/src
    ports:
      - "8004:8004"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/purchase_service/logs:/app/src/purchase_service/logs

  reporting_service:
    build: .
    environment:
      - SERVICE_NAME=reporting
      - DATABASE_URL=postgres://liquor_user:liquor_password@postgres:5432/liquor_db
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
      - DJANGO_SETTINGS_MODULE=reporting_service.settings
      - PYTHONPATH=/app:/app/src
    ports:
      - "8005:8005"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/reporting_service/logs:/app/src/reporting_service/logs

  accounting_service:
    build: .
    environment:
      - SERVICE_NAME=accounting
      - DATABASE_URL=postgres://liquor_user:liquor_password@postgres:5432/liquor_db
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
      - DJANGO_SETTINGS_MODULE=accounting_service.settings
      - PYTHONPATH=/app:/app/src
    ports:
      - "8006:8006"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/accounting_service/logs:/app/src/accounting_service/logs

volumes:
  postgres_data:
  redis_data: 